config/routes.rb
Rails.application.routes.draw do
  resources :investments, only: [:index, :new, :create]
  root to: 'investments#index'

  mount ActionCable.server => '/cable'

  resources :investments do
    collection do
      get 'export_json', defaults: { format: 'json' }
      post 'export_json', defaults: { format: 'json' }
      get 'export_csv', defaults: { format: 'csv' }
      post 'export_csv', defaults: { format: 'csv' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cryptocurrency.rb
class Cryptocurrency < ApplicationRecord
  has_many :investments
end

app/models/investment.rb
class Investment < ApplicationRecord
  belongs_to :cryptocurrency
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates_presence_of :cryptocurrency

  def calculate_annual_return
    monthly_return_rate = case cryptocurrency.symbol
                          when 'BTC' then 0.05
                          when 'ETH' then 0.042
                          when 'ADA' then 0.01
                          else 0
                          end

    initial_amount = amount
    annual_return = initial_amount * (1 + monthly_return_rate)**12 - initial_amount
    annual_return.round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptocurrencies_controller.rb
class CryptocurrenciesController < ApplicationController
  before_action :set_cryptocurrencies, only: [:export_json, :export_csv]

  def index
    @cryptocurrencies = Cryptocurrency.all
  end
end

app/controllers/investments_controller.rb
require 'csv'

class InvestmentsController < ApplicationController

  before_action :fetch_crypto_prices, only: [:index, :new, :export_json]

  def index
    @investments = Investment.all
  end

  def new
    @investment = Investment.new
  end

  def create
    @investment = Investment.new(investment_params)
    if @investment.save
      flash[:success] = 'Inversión exitosa.'
      redirect_to root_path
    else
      flash[:alert] = 'Error al crear la inversión.'
      redirect_back fallback_location: new_investment_path
    end
  end

  def destroy
    @investment = Investment.find(params[:id])
    @investment.destroy
    redirect_to root_path
  end

  def export_json
    Rails.logger.info(@cryptocurrencies.inspect)
    respond_to do |format|
      format.json do
        selected_data = @cryptocurrencies.map do |crypto|
          {
            name: crypto.name,
            symbol: crypto.symbol,
            current_price: crypto.current_price
          }
        end

        render json: selected_data
      end
    end
  end

  def export_csv
    respond_to do |format|
      format.csv do
        send_data to_csv, filename: 'cryptocurrencies_data.csv'
      end
    end
  end


  private

  def fetch_crypto_prices
    crypto_data = read_crypto_data_from_csv # Llamada a la función que lee el CSV
    update_crypto_instances(crypto_data)
    @cryptocurrencies = Cryptocurrency.all
  end

  def read_crypto_data_from_csv
    crypto_data = []
    CSV.foreach('./public/crypto_data.csv', headers: true) do |row|
      crypto_data << {
        name: row['Moneda'],
        monthly_interest: row['Interes_mensual'].to_f,
        balance: row['balance_ini'].to_f
      }
    end
    crypto_data
  end

  def update_crypto_instances(crypto_data)
    crypto_data.each do |data|
      symbol = case data[:name]
                when 'Bitcoin' then 'BTC'
                when 'Ether' then 'ETH'
                when 'Cardano' then 'ADA'
                else ''
                end

      crypto = Cryptocurrency.find_or_create_by(name: data[:name])
      crypto.update(monthly_interest: data[:monthly_interest], balance: data[:balance], current_price: fetch_price(symbol), symbol: symbol)

      @bitcoin_price = crypto.current_price if crypto.symbol == 'BTC'
      @ether_price = crypto.current_price if crypto.symbol == 'ETH'
      @cardano_price = crypto.current_price if crypto.symbol == 'ADA'
    end
  end

  def fetch_price(crypto_symbol)
    response = HTTParty.get("https://rest.coinapi.io/v1/exchangerate/#{crypto_symbol}/USD",
                            headers: { 'X-CoinAPI-Key' => '' })
    JSON.parse(response.body)['rate'] if response.success?
  end


  def to_csv
    attributes = %w{name symbol current_price}
    CSV.generate(headers: true) do |csv|
      csv << attributes

      if @cryptocurrencies.present?
        @cryptocurrencies.each do |crypto|
          csv << attributes.map { |attr| crypto.send(attr) }
        end
      end
    end
  end

  def investment_params
    params.require(:investment).permit(:cryptocurrency_id, :amount)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptocurrencies_helper.rb
module CryptocurrenciesHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/investments/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Lista de Inversiones</h1>

  <% @investments.each do |investment| %>
    <div class="card mb-3 mt-2">
      <div class="card-body">
        <%= image_tag("#{investment.cryptocurrency.symbol.downcase}.png", alt: investment.cryptocurrency.name, class: "img-fluid crypto-icon") %>
        <h5 class="card-title"><%= investment.cryptocurrency.name %>: <%= investment.amount %> USD</h5>
        <p class="card-text">
          Retorno Anual: <%= investment.calculate_annual_return %> USD <br>
          Retorno Anual en <%= investment.cryptocurrency.name %>: <%= (investment.calculate_annual_return / investment.cryptocurrency.current_price.to_f) unless investment.cryptocurrency.current_price.nil? %> <%= investment.cryptocurrency.symbol %>
        </p>

        <%= button_to 'Eliminar', investment_path(investment), method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' %>
      </div>
  
    </div>
  <% end %>

  <%= link_to 'Nueva Inversión', new_investment_path, class: 'btn btn-info mt-3' %>

  <h2 class="mt-5 mb-3">Criptomonedas</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Icono</th>
        <th>Nombre</th>
        <th>Precio Actual</th>
      </tr>
    </thead>
    <tbody id="crypto-table-body">
      <% @cryptocurrencies.each do |crypto| %>
        <tr>
          <td><%= image_tag("#{crypto.symbol.downcase}.png", alt: crypto.name, class: "img-fluid crypto-icon") %></td>
          <td>
            <%= crypto.name %><br>
            <small><%= crypto.symbol %></small>
          </td>
          <td class="crypto-price" data-symbol="<%= crypto.symbol %>"><%= crypto.current_price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="mt-3 d-flex justify-content-between">
    <%= button_to 'Exportar a JSON', { action: 'export_json' }, method: :post, remote: true, class: 'btn btn-primary' %>
    <%= button_to 'Exportar a CSV', { action: 'export_csv' }, method: :post, remote: true, class: 'btn btn-success' %>
  </div>

 
</div>

<!-- Script para manejar la exportación -->
<script>
  document.addEventListener('DOMContentLoaded', () => {
    const exportButtons = document.querySelectorAll('.btn-primary, .btn-success');

    exportButtons.forEach(button => {
      button.addEventListener('ajax:success', (event) => {
        const data = event.detail[0];
        const blob = new Blob([data], { type: 'application/octet-stream' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = button.textContent.trim().toLowerCase() + '_data.' + data.format;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      });
    });
  });
</script>

<% if flash[:success].present? %>
  <script>
    Swal.fire({
      icon: 'success',
      title: '<%= flash[:success] %>',
    });
  </script>
<% elsif flash[:alert].present? %>
  <script>
    Swal.fire({
      icon: 'error',
      title: '<%= flash[:alert] %>',
    });
  </script>
<% end %>

app/views/investments/new.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Nueva Inversión</h1>

  <p class="mb-3">Precio actual de Bitcoin: <%= @bitcoin_price %> USD</p>
  <p class="mb-3">Precio actual de Ether: <%= @ether_price %> USD</p>
  <p class="mb-3">Precio actual de Cardano: <%= @cardano_price %> USD</p>

  <%= form_with(model: @investment, url: investments_path, method: :post, class: 'mb-3') do |form| %>
    <div class="form-group">
      <%= form.label :cryptocurrency_id %>
      <%= form.collection_select(:cryptocurrency_id, Cryptocurrency.all, :id, :name, { prompt: 'Seleccione una criptomoneda' }, class: 'form-control', required: true) %>
    </div>

    <div class="form-group">
      <%= form.label :amount %>
      <%= form.number_field :amount, class: 'form-control', required: true, pattern: '\d+(\.\d{1,2})?' %>
    </div>

    <div class="form-group">
      <%= form.submit 'Crear Inversión', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <%= link_to 'Volver a la lista de inversiones', investments_path, class: 'btn btn-secondary' %>
</div>

<% if flash[:success].present? %>
  <script>
    Swal.fire({
      icon: 'success',
      title: '<%= flash[:success] %>',
    });
  </script>
<% elsif flash[:alert].present? %>
  <script>
    Swal.fire({
      icon: 'error',
      title: '<%= flash[:alert] %>',
    });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoInvestmentCalculator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
    <%= yield %>
  </body>
</html>